sudo: false
language: node_js
node_js:
  - '0.10'
deploy:
  - provider: npm
    email: serveradmin@octoblu.com
    api_key:
      secure: "miX7SK4ySAUMEfM6D2p0NfYT2UWpaKfXsE6YJaamHURoksyjTPL45UgVlY2w5kW293qZskWDEZiL0EUFY9bK6QVdOP0zPnBDKaRLM+IsToZA1sPGopz3l4KoDuhgmYkbh0MqW6WtDaET/Rxr/pmt0iFQ6JtRqu3bAP4+E/CXdSI="
    on:
      tags: true
      all_branches: true
